/* SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause */
/* Copyright(c) 2018-2019  Realtek Corporation. Constants from rtw88 rtw88xxa.h. */
#ifndef __RTW88XXA_H__
#define __RTW88XXA_H__

#define EFUSE_HW_CAP_IGNORE		0
#define EFUSE_HW_CAP_PTCL_VHT		3
#define EFUSE_HW_CAP_SUPP_BW80		7
#define EFUSE_HW_CAP_SUPP_BW40		6
#define EFUSE_READ_FAIL			0xff



#define WLAN_BCN_DMA_TIME			0x02
#define WLAN_TBTT_PROHIBIT			0x04
#define WLAN_TBTT_HOLD_TIME			0x064
#define WLAN_TBTT_TIME	(WLAN_TBTT_PROHIBIT |\
			(WLAN_TBTT_HOLD_TIME << BIT_SHIFT_TBTT_HOLD_TIME_AP))

struct rtw_jaguar_phy_status_rpt {
	__le32 w0;
	__le32 w1;
	__le32 w2;
	__le32 w3;
	__le32 w4;
	__le32 w5;
	__le32 w6;
} __packed;

#define RTW_JGRPHY_W0_GAIN_A		GENMASK(6, 0)
#define RTW_JGRPHY_W0_TRSW_A		BIT(7)
#define RTW_JGRPHY_W0_GAIN_B		GENMASK(14, 8)
#define RTW_JGRPHY_W0_TRSW_B		BIT(15)
#define RTW_JGRPHY_W0_CHL_NUM		GENMASK(25, 16)
#define RTW_JGRPHY_W0_SUB_CHNL		GENMASK(29, 26)
#define RTW_JGRPHY_W0_R_RFMOD		GENMASK(31, 30)

/* CCK: */
#define RTW_JGRPHY_W1_SIG_QUAL		GENMASK(7, 0)
#define RTW_JGRPHY_W1_AGC_RPT_VGA_IDX	GENMASK(12, 8)
#define RTW_JGRPHY_W1_AGC_RPT_LNA_IDX	GENMASK(15, 13)
#define RTW_JGRPHY_W1_BB_POWER		GENMASK(23, 16)
/* OFDM: */
#define RTW_JGRPHY_W1_PWDB_ALL		GENMASK(7, 0)
#define RTW_JGRPHY_W1_CFO_SHORT_A	GENMASK(15, 8)	/* s8 */
#define RTW_JGRPHY_W1_CFO_SHORT_B	GENMASK(23, 16)	/* s8 */
#define RTW_JGRPHY_W1_BT_RF_CH_MSB	GENMASK(31, 30)

#define RTW_JGRPHY_W2_ANT_DIV_SW_A	BIT(0)
#define RTW_JGRPHY_W2_ANT_DIV_SW_B	BIT(1)
#define RTW_JGRPHY_W2_BT_RF_CH_LSB	GENMASK(7, 2)
#define RTW_JGRPHY_W2_CFO_TAIL_A	GENMASK(15, 8)	/* s8 */
#define RTW_JGRPHY_W2_CFO_TAIL_B	GENMASK(23, 16)	/* s8 */
#define RTW_JGRPHY_W2_PCTS_MSK_RPT_0	GENMASK(31, 24)

#define RTW_JGRPHY_W3_PCTS_MSK_RPT_1	GENMASK(7, 0)
/* Stream 1 and 2 RX EVM: */
#define RTW_JGRPHY_W3_RXEVM_1		GENMASK(15, 8)	/* s8 */
#define RTW_JGRPHY_W3_RXEVM_2		GENMASK(23, 16)	/* s8 */
#define RTW_JGRPHY_W3_RXSNR_A		GENMASK(31, 24)	/* s8 */

#define RTW_JGRPHY_W4_RXSNR_B		GENMASK(7, 0)	/* s8 */
#define RTW_JGRPHY_W4_PCTS_MSK_RPT_2	GENMASK(21, 8)
#define RTW_JGRPHY_W4_PCTS_RPT_VALID	BIT(22)
#define RTW_JGRPHY_W4_RXEVM_3		GENMASK(31, 24)	/* s8 */

#define RTW_JGRPHY_W5_RXEVM_4		GENMASK(7, 0)	/* s8 */
/* 8812a, stream 1 and 2 CSI: */
#define RTW_JGRPHY_W5_CSI_CURRENT_1	GENMASK(15, 8)
#define RTW_JGRPHY_W5_CSI_CURRENT_2	GENMASK(23, 16)
/* 8814a: */
#define RTW_JGRPHY_W5_RXSNR_C		GENMASK(15, 8)	/* s8 */
#define RTW_JGRPHY_W5_RXSNR_D		GENMASK(23, 16)	/* s8 */
#define RTW_JGRPHY_W5_GAIN_C		GENMASK(30, 24)
#define RTW_JGRPHY_W5_TRSW_C		BIT(31)

#define RTW_JGRPHY_W6_GAIN_D		GENMASK(6, 0)
#define RTW_JGRPHY_W6_TRSW_D		BIT(7)
#define RTW_JGRPHY_W6_SIGEVM		GENMASK(15, 8)	/* s8 */
#define RTW_JGRPHY_W6_ANTIDX_ANTC	GENMASK(18, 16)
#define RTW_JGRPHY_W6_ANTIDX_ANTD	GENMASK(21, 19)
#define RTW_JGRPHY_W6_DPDT_CTRL_KEEP	BIT(22)
#define RTW_JGRPHY_W6_GNT_BT_KEEP	BIT(23)
#define RTW_JGRPHY_W6_ANTIDX_ANTA	GENMASK(26, 24)
#define RTW_JGRPHY_W6_ANTIDX_ANTB	GENMASK(29, 27)
#define RTW_JGRPHY_W6_HW_ANTSW_OCCUR	GENMASK(31, 30)

#define RF18_BW_MASK		(BIT(11) | BIT(10))

#endif
